image: ghcr.io/sushrut1101/docker:arch

variables:
  FOX_SYNC: "https://gitlab.com/OrangeFox/sync.git"
  CONFIG: "config.sh"

OrangeFox-CI:
  stage: build
  timeout: 3 hours
  script:
    - curl -sL https://raw.githubusercontent.com/sarthakroy2002/my_scripts/main/AOSP/twrp-build.sh | bash
